name: Build Docker image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/bonfhir/ig-toolbox:latest,ghcr.io/bonfhir/ig-toolbox:${{ github.sha }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.source=https://github.com/bonfhir/ig-devbox,annotation-index.org.opencontainers.image.description=A docker image to help with FHIR Implementation Guide authoring using FHIR Shorthand (FSH).